# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-21 13:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20171021_1456'),
    ]

    operations = [
        migrations.RenameField(
            model_name='treasure',
            old_name='img_url',
            new_name='image',
        ),
    ]
